### PR TITLE
Backup scheduling / Display Author field in new software node form / add NEUBIAS icon / fixed "Recent" link in the frontpage

### PR DESCRIPTION
**Pull request by miura**
5 last backups to be saved. Older files will be deleted automatically. 

"Author" field was not appearing in the form display - recovered so that it appears.

### CODE REVIEW

**Comment by PerrineGilloteaux** [comment]
Hi, data dumps are not necessary here , sql database is already backed up daily on the server

**Comment by miura** [comment]
Hi @PerrineGilloteaux  where are those dumps? If I do not have access to them, I want to keep this daily schedule.

**Comment by PerrineGilloteaux** [comment]
There is an every day back up, both on the sql server and on an expert an server with direct link access.
I would suggest than than when a dump is needed, just to add --port to the mysqldump command with one of the following:
Current copy: 3306
Yesterday: 3307
Last week: 3317

If another backup is needed, the daily dumps which are stored on a separate server during 30 days can be downloaded from the ovh client space.
The purpose is to avoid to take too much space of the server.
Then I would suggest than only the last backup is saved on the server by your script (just to have it ready if needed)? What do you think?

**Comment by miura** [comment]
@PerrineGilloteaux OK, I agree with just one backup. I will change this with this pull request.

**Comment by miura** [comment]
@PerrineGilloteaux  

1. Modified that the backup keeps only one file, not 5 files. 
2. replaced logos

If these are ok, then please merge these changes.

**Comment by miura** [comment]
Thanks @PerrineGilloteaux  I pulled this from test.biii.eu. Please check the site, and if it's OK, changes will be merged to the master branch.

**Comment by PerrineGilloteaux** [comment]
Hi @miura , seems fine to me. Just to be sure we are not loosing data here, you did not use the last version of the prod database (i.e older than 9 of May?) on test.biii.eu, did you? (compare for example http://test.biii.eu/sr-tesseler and biii.eu/sr-tesseler).

**Comment by miura** [comment]
@PerrineGilloteaux  test.biii database is in the downstream of biii, and current test.biii database is in the state of May 9th 2:50. So any additions in biii.eu later than that time point are not in test.biii.eu. So everything is OK.

**Pull request merged**
