### PR TITLE
New theme

### PR DESCRIPTION
**Pull request by alat54**

### CODE REVIEW

**Comment by miura** [comment]
Thanks @alat54 ! I will review the new theme!

**Comment by miura** [comment]
This pull request is now in the branch _dev20191022newTheme_ and is the current status of [test site](http://test.biii.eu). It will be merged to _dev_ branch first, and then will be deployed in the production site after checking/correcting missing features... and then this pull request will be closed.

**Comment by miura** [comment]
Hi @alat54 
Great, thanks! Could you resolve the conflicts above and do additional PR?
Cheers, 
Kota

**Comment by PerrineGilloteaux** [comment]
Hi Kota, I need to commit changes in configuration as well 

Le 10-03-2020 17:01, Kota Miura a écrit : 

> Hi @alat54 [1]
> Great, thanks! Could you resolve the conflicts above and do additional PR?
> Cheers,
> Kota 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].
 

Links:
------
[1] https://github.com/alat54
[2]
https://github.com/NeuBIAS/bise/pull/122?email_source=notifications&amp;email_token=AETERS6CCGDP3OA6JGPV3ELRGZP7HA5CNFSM4JCAICRKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEOMA4LQ#issuecomment-597167662
[3]

**Comment by miura** [comment]
> Hi Kota, I need to commit changes in configuration as well 

Please create a new PR!

**Pull request merged**
